[workspace]
resolver = "2"
members = [
    "crates/k-lib",
    "crates/k-ffi",
    "crates/k-bin",
    "crates/k-log",
]
exclude = ["assets/examples"]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"  # Optimize for size
panic = "abort"
