[workspace]
resolver = "2"
members = [
    "crates/kitchn_cli",
    "crates/kitchn_ffi",
    "crates/kitchn_lib",
    "crates/kitchn_log",
]
exclude = ["assets/examples"]

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"  # Optimize for size
panic = "abort"
