[meta]
name = "Cyberpunk Neon"

[settings]
active_icons = "nerdfont" # Reference to key in icons.toml

[colors]
# Special
bg = "#161925"
fg = "#F8F8F2"
cursor = "#8BE9FD"
selection_bg = "#44475A"
selection_fg = "#F8F8F2"

# Tabs
tabs = "#11131C"
tabs_active = "#BD93F9"

# Semantic (Hyprcore Mappings)
primary = "#FF79C6"    # light-magenta
secondary = "#BD93F9"  # light-blue
success = "#50FA7B"    # light-green
error = "#FF5555"      # light-red
warn = "#FFB86C"       # orange (Dracula)
info = "#8BE9FD"       # light-cyan
orange = "#FFB86C"     # orange

# Standard ANSI (Normal)
black = "#44475A"
red = "#DE312B"
green = "#2FD651"
yellow = "#D0D662"
blue = "#9C6FCF"
magenta = "#DE559C"
cyan = "#6AC5D3"
white = "#D7D4C8"

# Standard ANSI (Bright)
bright_black = "#656B84"
bright_red = "#FF5555"
bright_green = "#50FA7B"
bright_yellow = "#F1FA8C"
bright_blue = "#BD93F9"
bright_magenta = "#FF79C6"
bright_cyan = "#8BE9FD"
bright_white = "#F8F8F2"

[fonts]
# Exact system names (fc-list)
mono = "JetBrainsMono Nerd Font"
ui = "Roboto"
size_mono = "10"
size_ui = "11"
