language = "C"

[export]
include = [
    "hcore_context_new",
    "hcore_context_free",
    "hcore_get_last_error",
    "hcore_log",
    "hcore_pack",
    "hcore_unpack",
    "hcore_install",
    "HCoreContext"
]
